security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        api_user:
            id: DeliberryAPI\Core\Security\Application\Service\APIUserProvider

    firewalls:
        apiV1:
            pattern: ^/v1
            stateless: true
            provider: api_user
            custom_authenticators:
                    - DeliberryAPI\Core\Security\Application\Service\TokenAuthenticator


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }

