services:
  DeliberryAPI\Core\Common\Domain\Service\DateTimeService:
    class: DeliberryAPI\Core\Common\Infrastructure\Domain\Service\Php\PhpDateTimeService

  DeliberryAPI\Core\Common\Domain\Service\Serializer:
    class: DeliberryAPI\Core\Common\Domain\Service\Serializer
